---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dingyi.
--- DateTime: 2022/3/17 18:44
---


local Log = luajava.bindClass "android.util.Log"

function print(...)
    local buf = {}
    for n = 1, select("#", ...) do
        table.insert(buf, tostring(select(n, ...)))
    end
    local msg = table.concat(buf, "\t\t")
    Log.d("lua",tostring(luajava.getContext()))
    luajava.getContext().sendMsg(msg)
end

function onCreate()
    Log.d("lua","onCreate")
    print("onCreate")
end

function onDestroy()
    Log.d("lua","onDestroy")
    print("onDestroy")
end

function onResume()
    Log.d("lua","onResume")
    print("onResume")
end


